-- Removes em dashes ("—") from learn_articles (title/summary/body),
-- learn_categories.description, and plant_families.description, replacing
-- each with whichever of comma / period / parentheses / semicolon read most
-- naturally per sentence (elaborations and asides -> parentheses; separate
-- but related independent clauses -> semicolon; genuinely separate
-- sentences -> period; simple continuations -> comma). En dashes used for
-- number ranges (e.g. "50–100 images", "2017 and 2023" ranges elsewhere)
-- were left untouched. Part of the same broader pass as
-- ornamental_planting_advice.sql and care_field_em_dash_cleanup.sql.
--
-- learn_articles.body values use literal CRLF ("\r\n\r\n") paragraph
-- breaks matching the live data, hence the E'' string literals below.
--
-- Run via:
--   npx supabase db query --linked < supabase/em_dash_cleanup_articles.sql

-- =========================================================================
-- learn_articles (19 rows: id, summary and/or body)
-- =========================================================================

UPDATE learn_articles SET summary = E'A single protected area on your campus has been surveyed in detail by researchers, and the findings reveal a surprisingly rich forest right under your feet.',
    body = E'Most students walk past the UENR bat sanctuary every day without knowing what is inside it. In 2018, a team led by Owusu-Prempeh, Antobre, and Agyei published a botanical survey of the area in the Open Journal of Forestry, documenting 485 individual plants from 58 species spread across 25 different plant families. That makes it one of the most thoroughly documented small forest patches in West African academic literature.\r\n\r\nThe dominant species is Newbouldia laevis, the boundary tree, which accounts for nearly one in five of all individual plants in the sanctuary. Second is Griffonia simplicifolia, the climbing shrub whose seeds are the world''s primary commercial source of 5-HTP, a serotonin precursor used globally in antidepressant supplements. Together, these two species alone represent nearly a third of the sanctuary''s entire plant population.\r\n\r\nWhat makes the sanctuary ecologically significant is not just the species count but the carbon it stores. The same study calculated the carbon stock of the area, contributing to the growing body of Ghanaian research on university campus forests as carbon sinks. A 2025 study of three major Ghanaian campuses using the InVEST carbon model found that tree cover conversion to built areas had cost UG a 17.1% carbon loss and KNUST a 29.5% loss between 2017 and 2023, figures that underscore why protected areas like the UENR bat sanctuary matter far beyond their biodiversity value.\r\n\r\nThe sanctuary is called a bat sanctuary not because bats live in it, but because the dense canopy and fruit-bearing trees make it a critical foraging and roosting corridor for the fruit bat populations that disperse seeds across the wider campus. A follow-up study by Agyei-Ohemeng et al. documented which specific plant species bats were dispersing, and found Mallotus oppositifolius (16.1% of all seed deposits), Ficus exasperata (6.6%), and Solanum erianthum (6.2%) among the most frequently bat-moved seeds.\r\n\r\nThe next time you walk past the sanctuary, you are passing a research site, a carbon store, and a seed dispersal network, all simultaneously.'
WHERE id = 1;

UPDATE learn_articles SET body = E'Fruit bats are not just interesting animals. They are seed dispersers, pollinators, and ecosystem engineers, and UENR''s campus population of fruit bats depends directly on the trees documented in this app.\r\n\r\nAgyei-Ohemeng et al.''s seed trap study on the UENR campus placed collection traps across the campus and identified which plant species were being moved by bats through their droppings. The results showed a clear preference: bats were disproportionately dispersing seeds from Mallotus oppositifolius, a pioneer forest shrub, accounting for 16.1% of all seeds collected. This is significant because Mallotus is one of the first species to colonise disturbed forest gaps, meaning bats are actively driving the regeneration of the forest understory by choosing to eat and disperse its fruit.\r\n\r\nPaper Mulberry, Broussonetia papyrifera, was another frequently bat-dispersed species. This makes the Paper Mulberry trees on campus functionally important: they are not just trees, they are bat feeding stations that keep the dispersal network running.\r\n\r\nThe ecological relationship works in both directions. Bats need the trees for food. The trees need the bats to move their seeds beyond the shadow of the parent canopy, where seedlings have more light and less root competition to grow into. Remove the bats and the forest regeneration slows. Remove the trees and the bat population collapses. The bat sanctuary is not protecting bats from the campus; it is protecting the campus ecosystem from the fragmentation that would follow if the bat corridor were broken.\r\n\r\nThis is a textbook example of a mutualistic relationship that most people walk past every day without noticing.'
WHERE id = 2;

UPDATE learn_articles SET body = E'The numbers from Owusu-Prempeh et al.''s 2018 survey of the UENR bat sanctuary are worth sitting with for a moment. Fifty-eight plant species from 25 families in a protected area on a single university campus in Sunyani. For context, 25 families is a remarkable breadth of plant lineage diversity for such a small area; it reflects a forest community that developed over many decades without significant disturbance, allowing species from very different evolutionary backgrounds to coexist.\r\n\r\nThe family breakdown tells an interesting story. Fabaceae, the legume family, is well represented, which is ecologically useful because legumes fix atmospheric nitrogen, enriching the soil for other species. Moraceae, the fig family, provides keystone food resources for fruit bats and birds through its figs. Bignoniaceae, the family that includes both Newbouldia laevis and the African Tulip Tree, contributes showy-flowered species that attract pollinators.\r\n\r\nThe dominance of Newbouldia laevis at 19.4% of all individuals is consistent with its ecology: it is a fast-growing pioneer that quickly colonises gaps and secondary forest edges. Its cultural status as a sacred boundary tree across West Africa means it has historically been protected from cutting in many communities, giving it a competitive advantage in disturbed landscapes that other species do not have.\r\n\r\nWhat this diversity means practically for a plant identification app is that a student walking through the bat sanctuary with a phone could theoretically encounter more than half of all the species in this app''s database within a single walk. The sanctuary is not just an ecological feature of UENR; it is a field classroom that predates the construction of any actual classroom on campus.'
WHERE id = 3;

UPDATE learn_articles SET body = E'Approximately 75% of Ghanaians rely on traditional plant medicine as their first resort for health care, a figure documented in ethnobotanical surveys of the Akan people by researchers at Kumasi and reported in the PMC-indexed literature on Ghanaian traditional medicine. The ratio of medical doctors to traditional medical practitioners in Ghana stands at roughly 1:12,000, making plant-based treatment not a cultural curiosity but a functional public health system.\r\n\r\nEight species documented in this app are among the most-cited medicinal plants in Ghanaian ethnobotanical surveys.\r\n\r\nNeem (Azadirachta indica) sits at the top of almost every Ghanaian medicinal plant list. Its bark, leaves, and seeds are used to treat malaria, fever, skin disorders, and bacterial infections. Azadirachtin, isolated from its seeds, is also one of the most effective botanical pesticides known.\r\n\r\nMoringa (Moringa oleifera) ranked fourth in medicinal use value (SUV = 10.3) in the Bomaa community study in the Brong Ahafo region. Its leaves contain more vitamin C than oranges, more calcium than milk, and more iron than spinach, and it grows in virtually every part of Ghana.\r\n\r\nNewbouldia laevis is used for epilepsy, fever, and uterine colic. Peer-reviewed pharmacological studies have confirmed anticonvulsant activity in its leaf extracts.\r\n\r\nHolarrhena floribunda (Osese in Twi) has confirmed anti-inflammatory and antihistaminic properties in its stem bark, documented in a 2022 clinical study.\r\n\r\nGriffonia simplicifolia seeds contain up to 20% 5-HTP by weight (a natural serotonin precursor used globally for depression and insomnia).\r\n\r\nVoacanga africana (Ofruma in Twi) seeds yield voacangine, used to synthesise both ibogaine (anti-addiction) and vinpocetine (Alzheimer''s treatment).\r\n\r\nCastor Oil Plant (Ricinus communis) latex has documented purgative and skin-healing properties, though the raw seeds are highly toxic.\r\n\r\nPawpaw (Carica papaya) leaf extract is used across Ghana for malaria, platelet disorders, and dengue, with growing scientific support for the platelet-enhancing claim.\r\n\r\nThe forest outside your window is also a pharmacy.'
WHERE id = 4;

UPDATE learn_articles SET body = E'Griffonia simplicifolia is the second most abundant species in the UENR bat sanctuary, accounting for 9.3% of all 485 individuals documented in the 2018 botanical survey. Most people who walk past it see an unremarkable climbing shrub with dark leathery leaves and black seed pods. The global supplement industry sees something very different.\r\n\r\nGriffonia seeds contain up to 20% 5-hydroxytryptophan (5-HTP) by weight (the highest natural concentration of this serotonin precursor known in any plant). 5-HTP is a direct precursor to serotonin in the brain, which means it crosses the blood-brain barrier more readily than serotonin itself and is used in clinical settings and as a nutraceutical for depression, insomnia, anxiety, and appetite regulation.\r\n\r\nGiurleo et al.''s 2020 study published in ACS Publications specifically sampled Griffonia populations from Ghana and Liberia and confirmed the high 5-HTP content in West African specimens, documenting why West Africa (and Ghana in particular) is the world''s primary commercial source for wild-harvested Griffonia seeds.\r\n\r\nThe economic chain is significant. Forest communities in Ghana and Côte d''Ivoire hand-harvest Griffonia seed pods from wild populations. The seeds are cleaned, dried, and exported to pharmaceutical companies in Europe and North America where the 5-HTP is extracted and encapsulated. Almost every 5-HTP supplement sold in health food shops globally traces back to seeds harvested within a few hundred kilometres of where you are reading this.\r\n\r\nThe implications for conservation are serious. Griffonia is not cultivated commercially; wild populations are the sole source. As global demand for natural antidepressants grows, the pressure on wild Griffonia populations in Ghana''s forest zones increases proportionally. The UENR bat sanctuary is, among other things, an inadvertent conservation site for a globally traded pharmaceutical raw material.'
WHERE id = 5;

UPDATE learn_articles SET body = E'Voacanga africana is a modest-looking small tree in the Apocynaceae family, with glossy opposite leaves and small white flowers. It grows at the margins of secondary forests, exactly the habitat found around the UENR campus. Its local Akan name is Ofruma.\r\n\r\nWhat makes Voacanga globally significant is its seeds. They contain voacangine, an iboga alkaloid that serves as the primary starting material for the semi-synthesis of two pharmaceutical compounds.\r\n\r\nThe first is ibogaine, a psychoactive compound being actively researched as a treatment for opioid addiction and PTSD. Clinical trials at Johns Hopkins and other institutions have shown that a single supervised ibogaine session can dramatically reduce opioid cravings, an effect that has attracted significant pharmaceutical investment.\r\n\r\nThe second is vinpocetine, a compound derived from voacangine that is prescribed in many European countries and used as a supplement elsewhere for improving cerebral blood flow and cognitive function in patients with early Alzheimer''s disease and vascular dementia.\r\n\r\nGhana and neighbouring West African countries are among the world''s primary exporters of Voacanga seeds to pharmaceutical companies. This makes Voacanga africana (a tree most Ghanaians have never heard of) a significant contributor to global neurological medicine.\r\n\r\nThe traditional Akan knowledge of this plant predates its pharmaceutical applications. Ghanaian traditional medicine uses the bark, roots, and seeds of Voacanga to treat cardiovascular conditions, mental illness, and fever, uses that overlap meaningfully with what modern pharmacology later confirmed about the compound''s mechanisms.\r\n\r\nA lecturer in ecology at UENR noted in a 2024 Mongabay article about Ghana''s medicinal plants that traditional botanical knowledge is being transmitted effectively across generations in communities near campus. The risk is not loss of knowledge; it is loss of the trees themselves as forest clearance continues.'
WHERE id = 6;

UPDATE learn_articles SET body = E'The cooling effect of trees is not just a feeling. It is a measurable, documented physical process with significant implications for human comfort, energy use, and climate resilience, and the UENR campus is a live experiment in it every day.\r\n\r\nTrees cool their immediate environment through two main mechanisms. The first is shade: a mature tree canopy intercepts solar radiation before it reaches the ground surface, preventing the soil and any hard surfaces beneath from heating up. Research on tropical avenue trees including Peltophorum pterocarpum (the Yellow Flame Tree, which is present on the UENR campus) has documented canopy shade reducing soil surface temperature by up to 5°C.\r\n\r\nThe second mechanism is transpiration. Trees continuously release water vapour through their leaves, a process called transpiration. This is physically analogous to evaporative cooling: water evaporating from leaf surfaces absorbs heat from the surrounding air, lowering the local air temperature. A large tree can transpire hundreds of litres of water per day during the growing season, effectively running a continuous air conditioning process powered only by sunlight.\r\n\r\nThe Mast Tree (Monoon longifolium), with its tall columnar form and densely packed leaves, is particularly effective as a campus road buffer: studies have documented it reducing both heat and noise pollution along planted avenues. The Chinese Banyan (Ficus microcarpa) provides dense year-round shade and has one of the highest rates of CO2 absorption per unit of canopy area among common campus trees globally.\r\n\r\nThere is a compounding benefit. Cooler campus environments reduce the demand for air conditioning in nearby buildings, which reduces electricity consumption, which reduces the carbon emissions from power generation. The trees are cooling the campus in at least two ways simultaneously.'
WHERE id = 7;

UPDATE learn_articles SET summary = E'Several trees on the UENR campus are running a continuous underground fertiliser factory (for free). Here is how it works.',
    body = E'Nitrogen is the element that limits plant growth in more of the world''s soils than any other nutrient. Most plants cannot access atmospheric nitrogen directly, even though it makes up 78% of the air. They depend entirely on nitrogen that has already been converted into a soluble form in the soil.\r\n\r\nSeveral tree species on the UENR campus have evolved a workaround: they form symbiotic partnerships with soil bacteria that can fix atmospheric nitrogen directly, converting it into compounds the plant (and eventually the surrounding soil) can use. This process is called biological nitrogen fixation, and it is one of the most ecologically valuable services a tree can provide.\r\n\r\nLeguminous trees are the main nitrogen fixers on campus. Gliricidia sepium can fix up to 100 kg of nitrogen per hectare per year under good conditions, making it one of the most nitrogen-productive trees measured in tropical agroforestry research. Leucaena leucocephala has reported fixation rates even higher, with some studies documenting up to 500 kg N/ha/year in optimal conditions. Albizia julibrissin, the Silktree, fixes nitrogen through root nodule symbiosis and releases it into the surrounding soil through leaf litter as its feathery leaves decompose.\r\n\r\nCasuarina equisetifolia uses a different bacterial partner (Frankia rather than Rhizobium) but achieves substantial nitrogen fixation through the same root nodule mechanism. Interestingly, Casuarina is one of the few non-legumes that can fix nitrogen at ecologically significant rates.\r\n\r\nThe practical consequence is that trees growing next to nitrogen-fixing species often show better growth because the surrounding soil is being continuously enriched. Agroforestry systems across Ghana deliberately exploit this by intercropping food crops with Gliricidia and Leucaena, reducing or eliminating the need for synthetic fertiliser.'
WHERE id = 8;

UPDATE learn_articles SET body = E'Ficus (the fig genus) is arguably the most ecologically important group of plants in any tropical forest system. The UENR campus has at least two documented Ficus species: Ficus microcarpa, the Chinese Banyan, and Ficus exasperata, the Sandpaper Leaf Tree. Both are keystone species in ways that go far beyond their visual presence.\r\n\r\nThe fig-wasp mutualism is one of the most ancient and elaborate co-evolutionary relationships in the plant kingdom. Each Ficus species is pollinated by its own unique species of fig wasp, a relationship so specific that neither can reproduce without the other. Ficus microcarpa relies on Eupristina verticillata. The wasp enters the fig, deposits pollen, lays its eggs, and the next generation of wasps emerges coated in pollen to fly to another tree. The fig provides food, shelter, and a nursery for the wasp; the wasp provides the only means of fertilisation for the tree.\r\n\r\nFigs, once fertilised, become one of the most important food sources in tropical ecosystems. Birds, bats, primates, and dozens of invertebrate species eat figs, and because at least some Ficus species are fruiting in virtually every month of the year, figs function as a keystone food resource during periods when other fruits are scarce. Remove Ficus from a tropical forest and population crashes ripple across dozens of species that depend on it.\r\n\r\nFicus exasperata is additionally important on the UENR campus as a bat food source, documented in the Agyei-Ohemeng seed trap study as accounting for 6.6% of all bat-dispersed seeds. Its rough sandpaper leaves (caused by calcium carbonate cystoliths on the leaf surface) were traditionally used as a natural abrasive for smoothing wood and cleaning pots across West Africa.'
WHERE id = 9;

UPDATE learn_articles SET summary = E'Cassava feeds more than 500 million people and is the third-largest carbohydrate source in the tropics. It also contains a natural cyanide compound, and this is not a contradiction.',
    body = E'Manihot esculenta, cassava, was domesticated in tropical South America somewhere in the region of present-day Brazil and Paraguay, approximately 8,000 to 10,000 years ago. It arrived in West Africa with Portuguese traders in the 16th century and transformed the continent''s food security over the following centuries.\r\n\r\nThe paradox at the centre of cassava''s success is its toxicity. The roots and leaves contain linamarin, a cyanogenic glucoside that releases hydrogen cyanide when damaged, a defence mechanism against herbivores. In concentrated form, raw cassava is genuinely dangerous. Yet cassava became the most important root crop in sub-Saharan Africa precisely because of this characteristic: the same toxicity that makes it dangerous to eat raw makes it resistant to pests and diseases that devastate other root crops in tropical conditions.\r\n\r\nTraditional processing knowledge solved the toxicity problem completely. Peeling removes the outer bark where concentrations are highest. Soaking in water allows cyanide to leach out. Fermenting breaks down linamarin enzymatically. Drying removes remaining volatile compounds. The combination of two or more of these steps (applied intuitively by generations of West African farmers long before the biochemistry was understood) renders cassava completely safe to eat. Gari, fufu, and tapioca are all cassava products where effective traditional processing makes the underlying toxicity irrelevant.\r\n\r\nThe Cassava Leaf Disease Classification dataset available on Kaggle, with over 21,000 images of healthy and diseased cassava leaves from Uganda, gives a sense of how much disease pressure cassava faces in African farming contexts. In Ghana, cassava mosaic disease and cassava brown streak disease are the primary threats to yield, which is why the health classification feature in this app, even at its initial binary healthy/unhealthy level, has direct agricultural relevance for the cassava plants growing on and near campus.'
WHERE id = 10;

UPDATE learn_articles SET body = E'There is a common misconception about palm oil: that it is an introduced crop, an industrial invasion of tropical landscapes from Southeast Asia. In reality, Elaeis guineensis (the African Oil Palm) is native to West Africa, including Ghana. The large-scale plantations of Southeast Asia are growing a West African tree that was transplanted there during colonial-era agricultural expansion. The original home of the species is the forest-savannah transition zone across tropical West and Central Africa, exactly the region where UENR sits.\r\n\r\nA single hectare of oil palm produces more edible oil than any other crop known (roughly 3.7 tonnes per hectare per year, compared to 0.7 tonnes for rapeseed and 0.5 tonnes for sunflower). This extraordinary yield efficiency is why oil palm now produces over 35% of the world''s vegetable oil on just 10% of the land devoted to oil crops globally. The environmental debates around palm oil expansion are not about the crop itself but about the land use change (specifically the conversion of biodiverse tropical forest in Borneo and Sumatra to monoculture plantation).\r\n\r\nIn Ghana, the picture is different. Oil palm was part of the agricultural landscape long before the industrial era. Red palm oil, pressed from the outer fruit layer, is the primary cooking fat in Ghanaian cuisine and contains the highest concentration of beta-carotene of any plant food, making it a critical source of vitamin A in the Brong-Ahafo region where deficiency affects young children.\r\n\r\nThe tree itself is ecologically functional as well as economically important. Its fruit bunches support birds, bats, and primates. Its fronds are used for thatch, weaving, and boundary fencing. Its sap is tapped for palm wine. Every part of the plant has a documented use in Ghanaian traditional culture.'
WHERE id = 11;

UPDATE learn_articles SET body = E'At the beginning of the 20th century, Ghana was covered by approximately 8.2 million hectares of closed tropical forest, a contiguous canopy stretching from the coast into the Brong-Ahafo region and beyond. Systematic documentation of what happened over the following 120 years makes sobering reading.\r\n\r\nAgricultural expansion, logging, charcoal production, mining, and urbanisation have reduced that original forest to an estimated 1.4 to 1.6 million hectares today, a loss of more than 80%, and in the moist evergreen zones of the south, closer to 90% of original cover.\r\n\r\nThe consequences cascade through every ecological system. As Springer''s Environmental Management journal documented in a 2024 study of Ghana''s deforestation and rural livelihoods, the loss of forest cover increases runoff and soil erosion, reduces groundwater recharge, eliminates wildlife corridors, increases local temperatures, and removes the carbon stocks that make forests a primary tool in climate change mitigation.\r\n\r\nGhana''s government has responded with the Green Ghana Project, which planted over 42 million trees between 2021 and 2024, including the One-Student-One-Tree initiative that has specifically engaged students at Ghanaian universities. The Forest Carbon Partnership Facility paid Ghana USD 4.8 million in January 2023 for verified emissions reductions, the first carbon credit payment of this kind in West Africa.\r\n\r\nThe UENR bat sanctuary represents a fragment of what this forest once looked like across the region. Its 58 documented species in a small protected area hint at the extraordinary diversity that existed across millions of hectares before industrialisation. The species documented in this app are not just campus ornamentals; they are a living record of what Bono Ahafo''s forests contained before most of it was cleared.'
WHERE id = 12;

UPDATE learn_articles SET body = E'Invasive plant species are plants introduced (usually intentionally) outside their native range, where they establish self-sustaining populations that spread into natural ecosystems and outcompete native species. Three species documented in this app appear on the IUCN''s Global Invasive Species Database list of 100 worst invasive alien species.\r\n\r\nSphagneticola trilobata, the Creeping Daisy, is native to Mexico and Central America. Its yellow daisy flowers and easy propagation made it popular as a tropical groundcover. But it reproduces by rooting wherever a stem node touches moist soil, spreads several metres per season without producing seeds, and its photosynthetic rate is measurably higher than that of native West African relatives, meaning it consistently outcompetes them in direct competition. Once established, it forms dense mats that exclude virtually all other groundcover species. It is now in Ghana and across tropical Africa.\r\n\r\nSpathodea campanulata, the African Tulip Tree, has the most ironic invasive status: it is native to West Africa, including Ghana, yet it is listed as an invasive species in Hawaii, Florida, and parts of the Pacific, where escaped plantings have devastated native forest understories. Its prolific seeding and fast growth make it a landscape coloniser outside its native range.\r\n\r\nLeucaena leucocephala, planted across Ghana as an agroforestry nitrogen-fixer and live fence, has invaded natural savannahs and forest edges in many countries. It is now on multiple invasive species watchlists even while being promoted in others for its agricultural value.\r\n\r\nThe lesson is not that these plants should be removed from campus; that ship has largely sailed, and many of them provide genuine ecological services. The lesson is that the introduction of non-native plants anywhere is an experiment with outcomes that take decades to become visible.'
WHERE id = 13;

UPDATE learn_articles SET body = E'A lecturer in ecology at UENR, Bismark Ofosu-Bamfo, was quoted in a 2024 Mongabay investigation into Ghana''s medicinal plants making an observation that captures something important about the relationship between Akan culture and trees: "Some names of towns like Odumase may literally mean ''under the Odum tree'' (Milicia excelsa). A name like Onyina, which is a surname and also an appellation for a male born on Thursday (Yaw Onyina), is the same as the local name for Ceiba pentandra."\r\n\r\nThe Odum tree and the Ceiba are not merely plants in this cultural framework. They are reference points for human identity, the kind of landmarks that become surnames, town names, and ceremonial markers. This is a fundamentally different relationship to the plant world than the botanical one, and it has conservation consequences that no legislation has been able to replicate.\r\n\r\nTraditional tree protection in Akan culture operates through several mechanisms. Sacred groves, such as the bat sanctuary at UENR, are protected by cultural prohibition as much as by formal designation. Taboo days (in some Bono communities, Thursdays are days when no one enters the forest or goes to farm) reduce disturbance pressure cyclically. Boundary trees, particularly Newbouldia laevis, are legally untouchable under customary law: uprooting one without permission is considered a serious breach of community authority.\r\n\r\nAn ethnobotanical study of the Ejisu-Juaben Municipality in southern Ghana, published in PMC in 2019, found 106 medicinal plants in use from 45 families across the community, with leaves (52% of uses) and decoction (57.5% of preparation methods) as the dominant patterns. Contrary to the assumption that traditional knowledge is disappearing, the authors found similar levels of ethnobotanical knowledge across different ages, genders, religions, and educational levels, suggesting effective intergenerational transmission.\r\n\r\nThe plants in this app are not culturally neutral objects. Many of them carry histories that predate the university, the town of Sunyani, and the colonial boundaries that defined Ghana as a nation.'
WHERE id = 14;

UPDATE learn_articles SET body = E'Newbouldia laevis goes by several names across West Africa. In Nigeria it is called the Fertility Tree. In Ghana it is often called the Boundary Tree or the Living Fence. In Akan traditional governance, it functions as something closer to a legal marker, a living demarcation of land boundaries and sacred spaces that carries the authority of customary law.\r\n\r\nThe cultural logic is practical. Newbouldia is one of the easiest trees to propagate from cuttings; a stick of Newbouldia pushed into the ground at a land boundary will root and grow into a living marker that outlasts any fenced post, stone marker, or written document. Across the forest-savannah transition zone of West Africa, communities have been using living Newbouldia hedges as boundary markers for centuries. The tree has the additional quality of being rot-resistant and fire-resistant, which makes it useful for fence posts, building poles, and long-term boundary marking.\r\n\r\nThe cultural protection this creates is significant. Under Akan customary law as practised in communities near UENR, removing a Newbouldia boundary tree without the permission of both adjoining landowners is a serious legal matter, one that can be brought before the traditional chief''s court. This is informal but functional conservation: Newbouldia trees at boundaries are rarely cut because the social consequences are significant.\r\n\r\nThe UENR bat sanctuary''s dominance by Newbouldia, at 19.4% of all individual plants, reflects both its ecological fitness as a pioneer species and the accumulated effect of decades of cultural protection in the broader community. The tree is not dominant because it outcompetes everything else; it is dominant partly because it has been consistently left alone.'
WHERE id = 15;

UPDATE learn_articles SET summary = E'The UENR Flora app can classify whether a plant looks healthy or unhealthy. Here is what the human eye is actually looking for, and what those visual signs mean.',
    body = E'Plant health assessment at a basic level is pattern recognition, which is exactly what a neural network trained to distinguish healthy from unhealthy specimens is doing. Understanding what the model is looking for makes you a better observer and helps you understand why a confident healthy/unhealthy classification is more difficult than it first appears.\r\n\r\nYellowing leaves (chlorosis) is the most common visible signal of stress, but it is also the least specific. Leaves turn yellow when they cannot produce enough chlorophyll, which can happen because of nitrogen deficiency, iron deficiency in alkaline soils, waterlogging that suffocates roots, drought that shuts down nutrient uptake, or viral infection. Identifying which cause is responsible requires looking beyond the yellow colour itself, at the pattern of yellowing (between veins vs. whole leaf vs. tips and margins), the soil conditions, and recent weather.\r\n\r\nBrown leaf margins and tips are typically a desiccation signal: the leaf edges dry out first when the plant cannot deliver water to the extremities fast enough. This can be caused by drought, salt damage, chemical burn from pesticide, or physical damage from wind.\r\n\r\nSpots and lesions with defined margins are more diagnostic than general colour change. Circular brown spots with yellow halos often indicate fungal infection (anthracnose, leaf spot diseases). Water-soaked patches that turn brown suggest bacterial infection. Mosaic patterns of light and dark green tissue suggest viral infection, most commonly spread by aphids.\r\n\r\nPremature leaf drop, wilting that does not reverse overnight, and stunted new growth are systemic signals suggesting root damage, vascular disease, or severe nutrient deficiency.\r\n\r\nThe app''s binary healthy/unhealthy classification is a first-pass triage: it flags plants that show visible signs of stress for closer inspection. It is not a diagnostic tool, and this distinction matters; a human observer, a soil test, or a plant pathologist may be needed to identify the specific cause.'
WHERE id = 16;

UPDATE learn_articles SET body = E'Building a computer vision model that can reliably identify plant species is, in principle, an enormous problem. A model needs to learn that the same plant species looks different in morning light vs. afternoon, when wet vs. dry, when young vs. mature, when photographed from above vs. the side. Learning these invariances from scratch would require tens of thousands of training examples per species.\r\n\r\nTransfer learning is the technique that makes a practical alternative possible. The core idea is that a model already trained on millions of general images (the ImageNet dataset contains 14 million images across 20,000 categories) has already learned to recognise edges, textures, colour gradients, curved surfaces, and many other visual features that are useful for classifying anything, not just the categories it was originally trained on.\r\n\r\nMobileNetV2, the architecture used in this app''s classification model, was trained on ImageNet by Google. When we take this pre-trained model and fine-tune it on our campus plant dataset, the lower layers of the network (which encode general visual features like "this patch of texture looks rough" or "this edge is a curved boundary") can be left mostly unchanged. Only the higher-level layers, which make category-specific decisions, need to be retrained on our smaller dataset.\r\n\r\nThe result is that a dataset of 50–100 images per species, rather than the thousands that would be needed from scratch, is often sufficient to achieve useful classification accuracy. Sandler et al.''s 2018 CVPR paper introducing MobileNetV2 demonstrated that its architecture is specifically designed to be efficient at this kind of fine-tuning; its inverted residual blocks allow gradients to flow effectively during training with limited data.\r\n\r\nThe campus-specific benefit is that fine-tuning on locally collected photos teaches the model the specific lighting, backgrounds, and visual conditions present on the UENR campus, which is exactly the environment where the app will be used.'
WHERE id = 17;

UPDATE learn_articles SET summary = E'A peer-reviewed study using satellite imagery and the InVEST carbon model has now measured what Ghanaian campuses store, and what they have been losing.',
    body = E'In 2025, a study published in the journal Land (MDPI) applied the InVEST carbon model to three Ghanaian universities, the University of Ghana (UG), Kwame Nkrumah University of Science and Technology (KNUST), and University of Cape Coast (UCC), using ESRI land cover data at 10 metre resolution to measure how carbon storage had changed between 2017 and 2023.\r\n\r\nThe results were stark. UG lost 17.1% of its carbon stock (19,695 Mg C) over that six-year period. KNUST lost 29.5% (20,063 Mg C). UCC lost 7.9% (3,292 Mg C). All three losses were driven by the same cause: tree cover conversion to built areas as campuses expanded to accommodate growing student populations.\r\n\r\nThe study valued carbon using Ghana''s social cost of carbon (USD 0.97 per tonne of CO2), which allows the campus carbon losses to be expressed in economic terms. At this figure, KNUST''s six-year carbon loss represents a substantial economic cost in addition to its ecological cost, the loss of ecosystem services that no infrastructure project accounts for in its budget.\r\n\r\nThe researchers ran five future scenarios for each campus, modelling what happens under different development trajectories. The scenarios that maintained or increased tree cover consistently outperformed development-heavy scenarios on carbon storage, local temperature regulation, and biodiversity indicators.\r\n\r\nThis study directly affects how UENR should think about its own campus development. The bat sanctuary is an acknowledged carbon store. The question documented research is now asking is whether the broader campus is gaining or losing carbon as it develops. The species you can identify with this app are the biological units of that carbon store; each tree is a carbon budget line, and knowing which species they are is the first step toward quantifying what the campus holds.'
WHERE id = 18;

UPDATE learn_articles SET body = E'In January 2023, Ghana became the second country in Africa after Mozambique to receive payment from the Forest Carbon Partnership Facility (FCPF) for verified emissions reductions. The payment: USD 4.8 million for reducing approximately 972,000 tonnes of carbon emissions during the first monitoring period of its Emissions Reduction Payment Agreement (ERPA) with the World Bank.\r\n\r\nThe mechanism behind this payment is REDD+ (Reducing Emissions from Deforestation and Forest Degradation). Countries that can demonstrate, through satellite monitoring and ground-truthing, that they have reduced deforestation below a baseline level can sell the resulting carbon credits to buyers who use them to offset their own emissions. Ghana''s FCPF agreement provides for up to USD 50 million for 10 million tonnes of reduced emissions through 2024.\r\n\r\nGhana''s approach centres on the Ghana Cocoa Forest REDD+ Programme (GCFRP), which works with 140,000 farmers across 6 million hectares of the West Africa Guinean Forest. Farmers learn to plant shade trees within their cocoa plantations, which sequesters carbon, cools the crop, and often increases yields simultaneously. 69% of the FCPF payments are allocated directly to farmer groups and local communities.\r\n\r\nFor a UENR student, the relevance of this is direct. The trees in the bat sanctuary, on the campus roadsides, and in the wider Sunyani landscape are part of Ghana''s national carbon accounting. They represent verified economic value in a global market. Forest Resources Management is one of UENR''s core departments precisely because the country needs people trained to measure, manage, and maximise that value.\r\n\r\nThe plants in this app are not just botanical specimens; they are economic assets with quantified market values, provided they are still standing.'
WHERE id = 19;

-- =========================================================================
-- learn_categories (2 rows: id, description)
-- =========================================================================

UPDATE learn_categories SET description = 'From campus trees to your table (the stories of Ghana''s food plants).'
WHERE id = 4;

UPDATE learn_categories SET description = 'Trees as climate tools (what the research from Ghana actually shows).'
WHERE id = 8;

-- =========================================================================
-- plant_families (6 rows: id, description)
-- =========================================================================

-- Gentianaceae
UPDATE plant_families SET description = 'The gentian family, mostly herbs and shrubs, includes Anthocleista (unusual for producing large tropical trees).'
WHERE id = '835642bb-c823-4c9c-a73f-2c03ab32fdf7';

-- Apocynaceae
UPDATE plant_families SET description = 'The dogbane family includes frangipani, Holarrhena, Funtumia, and Bowstring Hemp; many produce toxic or medicinally active alkaloids.'
WHERE id = '84dc3967-d407-443b-ba91-fea48714bb70';

-- Musaceae
UPDATE plant_families SET description = 'The banana family includes large herbaceous monocots that produce bananas and plantains, staple foods in the tropics.'
WHERE id = '959fd809-563f-4087-a293-1d4ec6910f6c';

-- Poaceae
UPDATE plant_families SET description = 'The grass family, the world''s most economically important plant family, includes maize, rice, wheat, sugarcane, and teak''s grass relatives.'
WHERE id = 'b3c7aff9-2439-4a36-b544-bc0d7beb967f';

-- Asparagaceae
UPDATE plant_families SET description = 'The asparagus family includes Agave, Dracaena, and Cordyline, a diverse group of monocots from dry tropical regions.'
WHERE id = 'd88736b4-d8a2-4852-9b78-66dd1c8b3755';

-- Euphorbiaceae
UPDATE plant_families SET description = 'The spurge family includes cassava, castor oil plant, croton, and copperleaf, many with toxic or medicinal latex.'
WHERE id = 'f97b87e7-a918-4e9a-bb94-21690e902342';
